version: "3.7"

services:
    pvp-server:
        hostname: pvp_server_
        container_name: pvp_server
        image:  nwnxee/unified:c64661b
        env_file:
            - ${PWD-.}/config/common.env
            - ${PWD-.}/config/nwserver_dev.env
        stdin_open: true
        tty: true
        volumes:
            - ${PWD-.}/logs:/nwn/run/logs.0
            - ${PWD-.}/:/nwn/home
            - ${PWD-.}/logs:/nwn/data/bin/linux-x86/logs.0
        ports:
            - "5131:5131/udp"